name: Humble CI

on:
  push:
    branches:
      - master
          
jobs:
  humble_source:
    runs-on: ubuntu-22.04
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - run: sudo apt-get install ros-humble-pcl-*
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: pc2_coppeliasim
          target-ros2-distro: humble
